/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.css.bowlingkata;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.fail;

public class LibraryTest {
    @Test
    @DisplayName("test something library method")
    public void testSomeLibraryMethod() {
        fail();
    }
}
